import { Ingredient } from './models/ingredient';

export const ingredientsAllowed: Ingredient[] = [
  {
    id: 1,
    name: 'Anka',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 2,
    name: 'Fläsk',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 3,
    name: 'Hare',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 4,
    name: 'Häst',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 5,
    name: 'Kalkon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 6,
    name: 'Kanin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 7,
    name: 'Kyckling',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 8,
    name: 'Lamm',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 9,
    name: 'Nöt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 10,
    name: 'Struts',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 11,
    name: 'Viltkött (älg, ren mm)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 12,
    name: 'Hjärta',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 13,
    name: 'Lever',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 14,
    name: 'Njure',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 15,
    name: 'Blåmussla',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 16,
    name: 'Bläckfisk',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 17,
    name: 'Hummer',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 18,
    name: 'Krabba',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 19,
    name: 'Kräfta',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 20,
    name: 'Ostron',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 21,
    name: 'Pilgrimsmussla',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 22,
    name: 'Räka',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 23,
    name: 'Ansjovis',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 24,
    name: 'Fiskrom',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 25,
    name: 'Flundra',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 26,
    name: 'Gös',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 27,
    name: 'Hoki',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 28,
    name: 'Kaviar',
    aip: false,
    comment: 'Se innehåll',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 29,
    name: 'Kolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 30,
    name: 'Kummel',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 31,
    name: 'Lax',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 32,
    name: 'Löjrom',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 33,
    name: 'Makrill',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 34,
    name: 'Regnbågslax',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 35,
    name: 'Röding',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 36,
    name: 'Rödspätta',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 37,
    name: 'Sej',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },

  {
    id: 38,
    name: 'Sik',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 39,
    name: 'Sill',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 40,
    name: 'Stenbitsrom',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 41,
    name: 'Strömming',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 42,
    name: 'Tonfisk',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 43,
    name: 'Torsk',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 44,
    name: 'Öring',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 45,
    name: 'Samtliga fågelägg',
    aip: true,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 46,
    name: 'Ananas',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 47,
    name: 'Apelsin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 48,
    name: 'Aprikos',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 49,
    name: 'Aronia',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 50,
    name: 'Banan',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 51,
    name: 'Björnbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 52,
    name: 'Blåbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 53,
    name: 'Citron',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 54,
    name: 'Dadel',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 55,
    name: 'Fikon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 56,
    name: 'Granatäpple',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 57,
    name: 'Grapefrukt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 58,
    name: 'Hallon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 59,
    name: 'Havtorn',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 60,
    name: 'Hjortron',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 61,
    name: 'Honungsmelon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 62,
    name: 'Jordgubbar',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 63,
    name: 'Kiwi',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 64,
    name: 'Krusbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 65,
    name: 'Lime',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 66,
    name: 'Lingon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 67,
    name: 'Mango',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 68,
    name: 'Mullbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 69,
    name: 'Nektarin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 70,
    name: 'Nypon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 71,
    name: 'Papaya',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 72,
    name: 'Passionsfrukt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 73,
    name: 'Persika/nektarin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 74,
    name: 'Plommon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 75,
    name: 'Päron',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 76,

    name: 'Rabarber',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 77,
    name: 'Röda vinbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 78,
    name: 'Sharon, kaki',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 79,
    name: 'Mandarin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 80,
    name: 'Satsumas',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 81,
    name: 'Svarta vinbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 82,
    name: 'Körsbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 83,
    name: 'Tranbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 84,
    name: 'Vattenmelon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 85,
    name: 'Vindruvor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 86,
    name: 'Äpple',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 87,
    name: 'Jams',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 88,
    name: 'Jordärtskocka',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 89,
    name: 'Kassava',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 90,
    name: 'Morot',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 91,
    name: 'Palsternacka',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 92,
    name: 'Pepparrot',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 93,
    name: 'Persiljerot',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 94,
    name: 'Rotselleri',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 95,
    name: 'Rädisa',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 96,
    name: 'Rättika',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 97,
    name: 'Rova (majrova)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 98,
    name: 'Rödbeta',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 99,
    name: 'Svartrot',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 100,
    name: 'Sötpotatis',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 101,
    name: 'Groddar (alfalfa, från AIP-livsmedel)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 102,
    name: 'Gräslök',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 103,
    name: 'Gurka',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 104,
    name: 'Isbergssallat',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 105,
    name: 'Kronärtskocka',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 106,
    name: 'Lök (gul, röd)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 107,
    name: 'Mangold',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 108,
    name: 'Nori-tång',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 109,
    name: 'Nässla',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 110,
    name: 'Romansallat',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 111,
    name: 'Purjolök',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 112,
    name: 'Ruccola (senapskål)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },

  {
    id: 113,
    name: 'Rödlök',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 114,
    name: 'Schalottenlök',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 115,
    name: 'Selleri (stjälk)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 116,
    name: 'Sparris',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 117,
    name: 'Spenat',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 118,
    name: 'Vattenkrasse',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 119,
    name: 'Vitlök',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 120,
    name: 'Avokado',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 121,
    name: 'Butternutpumpa',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 122,
    name: 'Kokbanan/matbanan',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 123,
    name: 'Oliver',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 124,
    name: 'Pumpa',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 125,
    name: 'Squash',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 126,
    name: 'Zucchini',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 127,
    name: 'Blomkål',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 128,
    name: 'Broccoli',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 129,
    name: 'Brysselkål',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 130,
    name: 'Fänkål',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 131,
    name: 'Grönkål',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 132,
    name: 'Kinakål (salladskål)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 133,
    name: 'Kålrabbi',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 134,
    name: 'Pak-choi',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 135,
    name: 'Romansallat',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 136,
    name: 'Rödkål',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 137,
    name: 'Savojkål',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 138,
    name: 'Vitkål',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 139,
    name: 'Kålrabbi',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 140,
    name: 'Champinjon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 141,
    name: 'Karljohan',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 142,
    name: 'Kantarell',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 143,
    name: 'Shiitake',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 144,
    name: 'Blåstång',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 145,
    name: 'Havssallat',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 146,
    name: 'Kombu-tång',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 147,
    name: 'Kelp',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 148,
    name: 'Nori',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 149,
    name: 'Sjögräs',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 150,
    name: 'Wakame-tång',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 151,
    name: 'Ashwagandha',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 152,
    name: 'Aubergine',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 153,
    name: 'Chili',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 154,
    name: 'Gojibär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 155,
    name: 'Jalapeños',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 156,
    name: 'Paprika',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 157,
    name: 'Physalis',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 158,
    name: 'Potatis',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 159,
    name: 'Tomat',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 160,
    name: 'Gröna ärtor',
    aip: true,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 161,
    name: 'Sockerärtor',
    aip: true,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 162,
    name: 'Haricot verts',
    aip: true,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 163,
    name: 'Cashewnöt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 164,
    name: 'Hasselnöt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 165,
    name: 'Macadamianöt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 166,
    name: 'Paranöt (brazilnöt)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 167,
    name: 'Pekannöt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 168,
    name: 'Pinjenöt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 169,
    name: 'Pistagenöt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 170,
    name: 'Valnöt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 171,
    name: 'Chiafrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 172,
    name: 'Frökryddor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 173,
    name: 'Hampfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 174,
    name: 'Linfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 175,
    name: 'Pumpafrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 176,
    name: 'Sesamfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 177,
    name: 'Solrosfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 178,
    name: 'Kakao',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 179,
    name: 'Kastanj',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 180,
    name: 'Mandel',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 181,
    name: 'Basilika',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 182,
    name: 'Citrongräs',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 183,
    name: 'Citronmeliss',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 184,
    name: 'Dill',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 185,
    name: 'Dragon',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 186,
    name: 'Gräslök',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 187,
    name: 'Gurkmeja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },

  {
    id: 188,
    name: 'Havssalt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 189,
    name: 'Ingefära',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 190,
    name: 'Kamomill',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 191,
    name: 'Kapris',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 192,
    name: 'Kanel',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 193,
    name: 'Korianderblad',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 194,
    name: 'Kryddnejlika',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 195,
    name: 'Körvel',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 196,
    name: 'Lagerblad',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 197,
    name: 'Lavendel',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 198,
    name: 'Libbsticka',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 199,
    name: 'Mejram',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 200,
    name: 'Mynta',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 201,
    name: 'Pepparrot',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 202,
    name: 'Persilja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 203,
    name: 'Rosmarin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 204,
    name: 'Saffran',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 205,
    name: 'Salt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 206,
    name: 'Salvia',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 207,
    name: 'Timjan',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 208,
    name: 'Vaniljstång',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 209,
    name: 'Vaniljextrakt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 211,
    name: 'Wasabi',
    aip: false,
    comment: 'Se ingredienser',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 212,
    name: 'Örtsalt',
    aip: false,
    comment: 'Se ingredienser',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 213,
    name: 'Anisfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 214,
    name: 'Blandkryddor',
    aip: false,
    comment: 'Se ingredienser',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 215,
    name: 'Cayenne',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 216,
    name: 'Chili',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 217,
    name: 'Dillfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 218,
    name: 'Enbär',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 219,
    name: 'Fänkålsfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 220,
    name: 'Kardemumma',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 221,
    name: 'Peppar (svart, vit, grön)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 222,
    name: 'Stjärnanis',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 223,
    name: 'Korianderfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 224,
    name: 'Kumminfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 225,
    name: 'Muskotnöt',

    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 226,
    name: 'Paprikapulver',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 227,
    name: 'Rödpeppar',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 228,
    name: 'Senapsfrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 229,
    name: 'Sellerifrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 230,
    name: 'Vallmofrö',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 231,
    name: 'Ankfett',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 232,
    name: 'Avokadoolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 233,
    name: 'Ghee',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 234,
    name: 'Ister',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 235,
    name: 'Kokosolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 236,
    name: 'Olivolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 237,
    name: 'Smör',
    aip: true,
    comment: 'Ingår i vissa tolkningar av paleo',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 238,
    name: 'Arrowrootmjöl',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 239,
    name: 'Bikarbonat',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 240,
    name: 'Carob',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 241,
    name: 'Gelatin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 242,
    name: 'Honung',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 243,
    name: 'Jordmandelmjöl (tigernöt)',
    aip: true,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 244,
    name: 'Kassavamjöl',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 245,
    name: 'Kokbanan',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 246,
    name: 'Kokosmjöl',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 247,
    name: 'Kokossocker',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 248,
    name: 'Kollagenpulver',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 249,
    name: 'Mandelmjöl',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 250,
    name: 'Nötmjöler',
    aip: true,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 251,
    name: 'Potatismjöl',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 252,
    name: 'Riven kokos',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 253,
    name: 'Tapiokamjöl',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 254,
    name: 'Ansjovis (som krydda)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 255,
    name: 'Coconut aminos (krydda)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 256,
    name: 'Fisksås',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 257,
    name: 'Kokosmjölk',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 258,
    name: 'Kokosgrädde',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 259,
    name: 'Äppelcidervinäger',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 260,
    name: 'Benbuljong',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 261,
    name: 'Ingefärste',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 262,
    name: 'Kaffe',
    aip: true,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 263,
    name: 'Rooiboste',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 264,
    name: 'Te (svart, rött, grönt)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 265,
    name: 'Vatten (naturligt smaksatt)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 266,
    name: 'Alkoholhaltiga drycker',
    aip: true,
    comment: 'Kan ingå i paleo, men begränsa',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 267,
    name: 'Syrade livsmedel (introducera långsamt): Kokosyoghurt, Kombucha, Surkål, Syrade grönsaker',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: true,
  },
  {
    id: 267,
    name: 'Havre',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 268,
    name: 'Korn',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 269,
    name: 'Majs',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 270,
    name: 'Ris',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 271,
    name: 'Råg',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 272,
    name: 'Vete',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 273,
    name: 'Amarant',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 274,
    name: 'Bovete',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 275,
    name: 'Quinoa',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 276,
    name: 'Teff',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 277,
    name: 'Black-eye-bönor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 278,
    name: 'Gula ärter',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 279,
    name: 'Jordnötter',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 280,
    name: 'Kidneybönor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 281,
    name: 'Kikärtor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 282,
    name: 'Limabönor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 283,
    name: 'Linser',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 284,
    name: 'Mungbönor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 285,
    name: 'Sojabönor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 286,
    name: 'Svarta bönor',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 287,
    name: 'Linfröolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 288,
    name: 'Majsolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 289,
    name: 'Matolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 290,
    name: 'Rapsolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 291,
    name: 'Sojaolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 292,
    name: 'Solrosolja',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 293,
    name: 'Agave',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 294,
    name: 'Dadelsirap',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 295,
    name: 'Farin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 296,
    name: 'Fruktos',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 297,
    name: 'Galaktos',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 298,
    name: 'Maltos',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 299,
    name: 'Majssocker',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 300,
    name: 'Inulin',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 301,
    name: 'Sirap',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 302,
    name: 'Rissirap',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 303,
    name: 'Råsocker',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 304,
    name: 'Rörsocker',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 305,
    name: 'Vitt socker',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 306,
    name: 'Sulfiter (E 220-224)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 307,
    name: 'Fosfater (E 338-41, E 343, E 450-52)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 308,
    name: 'Färgämnen (E 100-180)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 309,
    name: 'Smakförstärkare (E 620-625)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 310,
    name: 'Emulgeringsmedel (samtliga, E 400-495)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 311,
    name: 'Guargummi och guarkärnmjöl (E 412)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 312,
    name: 'Xantangummi (E 415)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 313,
    name: 'Lecitin (E 322)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 314,
    name: 'Hydrolyserat protein från majs, soja, ris eller vete',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 315,
    name: 'Sorbitol (E 420)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 316,
    name: 'Maltitol (E 421)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 317,
    name: 'Sackarin (E 954)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 318,
    name: 'Aspartam (E 951)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 319,
    name: 'Sucralos (E 955)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 320,
    name: 'Erytritol (E 968)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 321,
    name: 'Grädde',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 322,
    name: 'Keso',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 323,
    name: 'Kondenserad mjölk',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 324,
    name: 'Kvarg',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 325,
    name: 'Mjölk',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 326,
    name: 'Ost (ko, get, får)',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 327,
    name: 'Vassleprotein',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
  {
    id: 328,
    name: 'Yoghurt',
    aip: false,
    comment: '',
    ingredientClass: null,
    allowed: false,
  },
];
